Description of es_BASEDIR
Home > elasticity_sampling > es_BASEDIR.m
es_BASEDIR
PURPOSE
ES_BASEDIR - Determine directory in which ES toolbox resides
SYNOPSIS
function d = es_BASEDIR()
DESCRIPTION
 ES_BASEDIR - Determine directory in which ES toolbox resides
 d = es_BASEDIR()
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
es_figure_3_hepatonet_atp_glucose_o2 Elasticity sampling: analysis of hepatonet ATP regeneration network
es_figure_4_hepatonet_utp_paradoxical Hepatonet elasticity sampling // analysis for UTP rephosphorylation
es_figure_5_synergies Run elasticity sampling and analyse synergies
es_figure_6_metabolic_correlations Prediction of static metabolite fluctuations for different types of
es_figure_7_energetics_control_and_noise How do reaction affinities influence control coefficients and chemical noise?
demo_e_coli_glycolysis demo_e_coli_glycolysis - Demo script for thermodynamically feasible elasticity sampling
elasticity_sampling_workflow elasticity_sampling_workflow - Demo script