Description of es_compare_ensembles
Home > elasticity_sampling > es_compare_ensembles.m
es_compare_ensembles
PURPOSE
ES_COMPARE_ENSEMBLES - Compare an output function between two model ensembles
SYNOPSIS
function res = es_compare_ensembles(output1, output2, n_per, fdr, verbose)
DESCRIPTION
 ES_COMPARE_ENSEMBLES - Compare an output function between two model ensembles
 res = es_compare_ensembles(output1, output2, n_per, fdr, verbose)
 Significance test for model outputs obtained from multiple elasticity sampling
 Significant differences are computed from the outputs of a previous multiple
 elasticity sampling for two model variants (see 'es_sample_multiple').
 Both model variants must have the same number of metabolites and reactions.
 Inputs
   output1  - Matrix or tensor from 1st model variant (from 'es_sample_multiple')
   output2  - Matrix or tensor from 2nd model variant (from 'es_sample_multiple')
   n_per    - Number of samples in permutation test
   fdr      - False discovery rate
 Output: Data structure 'res' with fields:
   res.mean_total               - Mean value for all samples (total mean)
   res.mean_a                   - Mean value for 1st variant
   res.mean_b                   - Mean value for 2nd variant
   res.mean_delta               - Difference between values for both variants
   res.p_value_mean_total       - p value of [mean value for all samples ~= total mean]
   res.p_value_mean_a           - p value of [mean value for 1st variant ~= total mean]
   res.p_value_mean_b           - p value of [mean value for 2nd variant ~= total mean]
   res.p_value_mean_delta       - p value of [difference between values for both variants
                                - ~= difference between values from shuffled variants]
   res.mean_total_significant   - Significant elements for mean value for all samples
   res.mean_a_significant       - Significant elements for mean value for 1st variant
   res.mean_b_significant       - Significant elements for mean value for 2nd variant
   res.mean_delta_significant   - Significant elements for difference between variants
                                - Values: 1 (significantly high),  -1 (significantly low)
   res.n_mean_total_significant - # significant elements for mean value for all samples
   res.n_mean_a_significant     - # significant elements for mean value for 1st variant
   res.n_mean_b_significant     - # significant elements for mean value for 2nd variant
   res.n_mean_delta_significant - # significant elements for difference between variants
CROSS-REFERENCE INFORMATION
This function calls:
influence_anova INFLUENCE_ANOVA - Anova of a variable characterising single reactions
interaction_anova INFLUENCE_ANOVA - Anova of a variable characterising pairs reactions
This function is called by:
demo_elasticity_sampling_glycolysis demo_elasticity_sampling_glycolysis - Demo script for thermodynamically feasible elasticity sampling
demo_elasticity_sampling_workflow elasticity_sampling_workflow - Demo script