Description of es_reference_state
Home > elasticity_sampling > elasticity_sampling > es_simple > es_reference_state.m
es_reference_state
PURPOSE
ES_REFERENCE_STATE - Elasticity sampling
SYNOPSIS
function [result, fluxes, es_options, es_constraints] = es_reference_state(network, es_options, es_constraints)
DESCRIPTION
ES_REFERENCE_STATE - Elasticity sampling
 [result, fluxes, es_options, es_constraints] = es_reference_state(network, es_options, es_constraints)
 Construct a reference state and compute the elasticities,
 assuming half-saturation (i.e., saturation values alpha = 0.5)
 This function is a wrapper around 'es_sample_model.m'
CROSS-REFERENCE INFORMATION
This function calls:
es_sample_model ES_SAMPLE_MODEL - Sample all model parameters for a network
This function is called by:
es_figure_3_hepatonet_atp_glucose_o2 Elasticity sampling: analysis of hepatonet ATP regeneration network
es_model_to_sampling ES_MODEL_TO_SAMPLING - Wrapper function for es_reference_state plus some graphics routines