Description of demo_elasticity_sampling_workflow
Home > elasticity_sampling > demo > demo_elasticity_sampling_workflow.m
demo_elasticity_sampling_workflow
PURPOSE
elasticity_sampling_workflow - Demo script
SYNOPSIS
This is a script file.
DESCRIPTION
 elasticity_sampling_workflow - Demo script
 Demo script for thermodynamically feasible elasticity sampling
 In this script, we load a metabolic network model, run elasticity sampling
 with two types of rate laws, and compare the results of the two model ensembles
CROSS-REFERENCE INFORMATION
This function calls:
es_dependencies ES_DEPENDENCIES - Check for dependencies of the ES toolbox
es_BASEDIR ES_BASEDIR - Determine directory in which ES toolbox resides
es_compare_ensembles ES_COMPARE_ENSEMBLES - Compare an output function between two model ensembles
es_default_options ES_DEFAULT_OPTIONS - Set default values in 'es_options' and 'es_constraints'
es_sample_model ES_SAMPLE_MODEL - Sample all model parameters for a network
es_sample_multiple ES_SAMPLE_MULTIPLE - Create model ensemble and collect values for an output function
This function is called by: