Description of energetics_control_and_noise
Home > elasticity_sampling > elasticity_sampling > es_metabolite_fluctuations > energetics_control_and_noise.m
energetics_control_and_noise
PURPOSE
ENERGETICS_CONTROL_AND_NOISE - Analyse control coefficients and noise levels (assuming uniform white noise in each reaction!)
SYNOPSIS
function [Sigma_c, Sigma_j, Sigma_c_list, Sigma_j_list, Sigma_c_specific_1Hertz, Sigma_j_specific_1Hertz] = energetics_control_and_noise(network,network_CoHid, c, v, mu, omega_list, tau_list, omega_fast, omega_slow, psfile_dir, basename, es_options, es_constraints, volume)
DESCRIPTION
ENERGETICS_CONTROL_AND_NOISE - Analyse control coefficients and noise levels (assuming uniform white noise in each reaction!)
[Sigma_c, Sigma_j, Sigma_c_list, Sigma_j_list, Sigma_c_specific_1Hertz, Sigma_j_specific_1Hertz] = energetics_control_and_noise(network,network_CoHid, v, mu, omega_list, tau_list, psfile_dir, basename, es_options, es_constraints, volume)
 Recommended units:
  Enzyme levels in  mol
  Volume            m^3
  Metabolite levels mM
  Fluxes            mol/s
  Accordingly, the spectral densities will be in mM^2 and (mol/s)^2
 Spectral densities are computed under the assumption that white noise
 has a spectral density of 1. If white noise is defined as having a covariance
 given by the Dirac delta function (with prefactor 1), as assumed in the
 chemical Langevin equation, this corresponds to a Fourier transformation
 with prefactor 1 for the transformation omega -> t and prefactor 1/2pi for the
 transformation t -> omega
CROSS-REFERENCE INFORMATION
This function calls:
es_default_options ES_DEFAULT_OPTIONS - Set default values in 'es_options' and 'es_constraints'
es_sample_model ES_SAMPLE_MODEL - Sample all model parameters for a network
This function is called by:
es_figure_7_energetics_control_and_noise How do reaction affinities influence control coefficients and chemical noise?