Description of demo_es_sampling
Home > demo > demo_es_sampling.m
demo_es_sampling
PURPOSE
Demo script for thermodynamically feasible elasticity sampling
SYNOPSIS
This is a script file.
DESCRIPTION
 Demo script for thermodynamically feasible elasticity sampling
CROSS-REFERENCE INFORMATION
This function calls:
es_default_options [es_options, es_constraints] = es_default_options(N)
es_sample_model result = es_sample_model(N, W, ind_ext, es_constraints, es_options)
es_sample_multiple [output, output_list] = es_sample_multiple(N, W, ind_ext, es_constraints, es_options, output_function, select_function, score_function, function_args)
es_significant_differences es_significant_differences(output1,output2)
This function is called by:
SOURCE CODE
% Demo script for thermodynamically feasible elasticity sampling
cd /home/wolfram/matlab/projects/elasticity_sampling/elasticity_sampling/es/demo
% ------------------------------------------------------
% Load network model
% Alternative SBML: network = sbml2network('data/ecoli_glycolysis_network.xml');
network = sbtab_to_network('data/ecoli_glycolysis');
network = netgraph_make_graph(network);
network = netgraph_read_positions(network,'data/ecoli_glycolysis_Positions.tsv');
N       = network.N;                  % stoichiometric matrix
W       = network.regulation_matrix;  % allosteric regulation matrix
ind_ext = find(network.external);     % external metabolites (indices)
K = full(network_analyse(network));   % stationary fluxes
v = K(:,1) * sign(K(1));
% ------------------------------------------------------
% Run single elasticity sampling
[es_options,es_constraints] = es_default_options(N);
es_constraints.v_fix = v;
result = es_sample_model(network.N, W, ind_ext, es_constraints, es_options);
% ------------------------------------------------------
% Run multiple elasticity sampling (condition 1)
es_options.n_samples         = 10;
es_options.set_alpha_to_half = 0;
% sum of squares of all flux control coefficients
output_function      = inline('sum(result.control.CJ .^2)','result','other');
es_options.kinetic_law = 'cs';
output1 = es_sample_multiple(N, W, ind_ext, es_constraints, es_options, output_function);
es_options.kinetic_law = 'ms';
output2 = es_sample_multiple(N, W, ind_ext, es_constraints, es_options, output_function);
% ------------------------------------------------------
% Find significant differences between both conditions
false_discovery_rate = 0.05;
res = es_significant_differences(output1, output2, false_discovery_rate);