Description of es_figure_5_synergies
Home > elasticity_sampling > demo > article_figures > es_figure_5_synergies.m
es_figure_5_synergies
PURPOSE
Run elasticity sampling and analyse synergies
SYNOPSIS
This is a script file.
DESCRIPTION
 Run elasticity sampling and analyse synergies
 See Article Figure 5
CROSS-REFERENCE INFORMATION
This function calls:
log_epistasis LOG_EPISTASIS Simple epistasis measure
segre_epistasis ES_SEGRE_EPISTASIS Segre's epistasis measure
es_BASEDIR ES_BASEDIR - Determine directory in which ES toolbox resides
es_default_options ES_DEFAULT_OPTIONS - Set default values in 'es_options' and 'es_constraints'
es_sample_model ES_SAMPLE_MODEL - Sample all model parameters for a network
This function is called by: