Description of es_figure_4_hepatonet_utp_paradoxical
Home > elasticity_sampling > demo > article_figures > es_figure_4_hepatonet_utp_paradoxical.m
es_figure_4_hepatonet_utp_paradoxical
PURPOSE
Hepatonet elasticity sampling // analysis for UTP rephosphorylation
SYNOPSIS
This is a script file.
DESCRIPTION
 Hepatonet elasticity sampling // analysis for UTP rephosphorylation
 Analysis of effective self-inhibition
 Example anaerobic UTP rephosphorylation with saturation values alpha = 0.5 in reference state
CROSS-REFERENCE INFORMATION
This function calls:
es_BASEDIR ES_BASEDIR - Determine directory in which ES toolbox resides
es_sample_model ES_SAMPLE_MODEL - Sample all model parameters for a network
es_sample_multiple ES_SAMPLE_MULTIPLE - Create model ensemble and collect values for an output function
This function is called by: