Description of es_figure_3_hepatonet_atp_glucose_o2
Home > elasticity_sampling > demo > article_figures > es_figure_3_hepatonet_atp_glucose_o2.m
es_figure_3_hepatonet_atp_glucose_o2
PURPOSE
Elasticity sampling: analysis of hepatonet ATP regeneration network
SYNOPSIS
This is a script file.
DESCRIPTION
 Elasticity sampling: analysis of hepatonet ATP regeneration network
 See Article Figure 3
CROSS-REFERENCE INFORMATION
This function calls:
es_reference_state ES_REFERENCE_STATE - Elasticity sampling
es_BASEDIR ES_BASEDIR - Determine directory in which ES toolbox resides
es_default_options ES_DEFAULT_OPTIONS - Set default values in 'es_options' and 'es_constraints'
This function is called by: